<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.31.0" />
    <PackageReference Include="Binance.Net" Version="11.7.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.58" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CryptoHft.Application\CryptoHft.Application.csproj" />
    <ProjectReference Include="..\CryptoHft.Domain\CryptoHft.Domain.csproj" />
  </ItemGroup>
</Project>
